"""second revision

迁移 ID: 4f8ac90c4423
父迁移: 5a2fce2f15b6
创建时间: 2024-12-17 05:05:43.564984

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '4f8ac90c4423'
down_revision: str | Sequence[str] | None = '5a2fce2f15b6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ninja3_giftcodes')
    op.drop_table('ninja3_users')
    op.drop_table('ninja3_gameids')
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ninja3_gameids',
    sa.Column('game_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('game_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ninja3_users',
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('uid_nums', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('need_remind', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ninja3_giftcodes',
    sa.Column('code', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('time', sa.DATE(), nullable=False),
    sa.Column('available', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('code'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
