"""first revision

迁移 ID: e9081ee5fcc6
父迁移: 
创建时间: 2025-03-01 07:55:08.812317

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'e9081ee5fcc6'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('chat',)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_usermessage',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_bot_reply', sa.Boolean(), nullable=False),
    sa.Column('target_user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_mentioned', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('record_id', name=op.f('pk_chat_usermessage')),
    info={'bind_key': 'chat'}
    )
    op.drop_table('deepseekapi_usermessage')
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deepseekapi_usermessage',
    sa.Column('record_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('nickname', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('group_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('is_bot_reply', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('target_user_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('is_mentioned', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('record_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('chat_usermessage')
    # ### end Alembic commands ###
