"""second revision

迁移 ID: 66e41daece75
父迁移: 867b1e235ee3
创建时间: 2025-03-04 13:06:51.971981

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '66e41daece75'
down_revision: str | Sequence[str] | None = '867b1e235ee3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deepseek_userinfo',
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('warning_times', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_deepseek_userinfo')),
    info={'bind_key': 'deepseek'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deepseek_userinfo')
    # ### end Alembic commands ###
