"""first revision

迁移 ID: 867b1e235ee3
父迁移: 
创建时间: 2025-03-02 07:31:18.976988

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '867b1e235ee3'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('deepseek',)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deepseek_groupmessage',
    sa.Column('message_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('is_bot_msg', sa.Boolean(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('message_id', name=op.f('pk_deepseek_groupmessage')),
    info={'bind_key': 'deepseek'}
    )
    op.create_table('deepseek_privatemessage',
    sa.Column('message_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('is_bot_msg', sa.Boolean(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('message_id', name=op.f('pk_deepseek_privatemessage')),
    info={'bind_key': 'deepseek'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deepseek_privatemessage')
    op.drop_table('deepseek_groupmessage')
    # ### end Alembic commands ###
